### ISSUE TITLE
function for 6 BWB condition colours from SEMA-Berlin 1

### ISSUE THREAD

**Issue by mriech** [KWB-R/sema.berlin.utils#2]
Hi Hauke, could you please add the six condition colours we used at the beginning of SEMA-Berlin 1 to the function "get_bwb_colours", or similar? I would like to use it for one of the plots requested by BWB for the data preparation output. So far the six colour were defined here, if I remember correctly: ...R_Development\RScripts\SEMA\lib\SEMA_functions_colour.R.

**Comment by hsonne** [comment]
Done. Reinstall from "dev" branch and call `get_bwb_colours(six = TRUE)` to get the six colours.

**Comment by mriech** [comment]
Worked fine. Thanks.

Von: Hauke Sonnenberg <notifications@github.com>
Gesendet: Dienstag, 19. Januar 2021 16:21
An: KWB-R/sema.berlin.utils <sema.berlin.utils@noreply.github.com>
Cc: Mathias Riechel <Mathias.Riechel@kompetenz-wasser.de>; Author <author@noreply.github.com>
Betreff: Re: [KWB-R/sema.berlin.utils] function for 6 BWB condition colours from SEMA-Berlin 1 (#2)


Done. Reinstall from "dev" branch and call get_bwb_colours(six = TRUE) to get the six colours.
